name: Tests

on:
    push:
        branches:
            - master
    pull_request:
    schedule:
        - cron: '10 6 * * 1'

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - { php-version: 8.1, orm-version: '', dependency-version: prefer-lowest }
                    - { php-version: 8.3, orm-version: '^2.20', dependency-version: prefer-stable }
                    - { php-version: 8.3, orm-version: '^3.0', dependency-version: prefer-stable }
                    - { php-version: 8.4, orm-version: '^2.20', dependency-version: prefer-stable }
                    - { php-version: 8.4, orm-version: '^3.0', dependency-version: prefer-stable }
        name: PHPUnit (PHP ${{matrix.php-version}}, Doctrine ORM version lock ${{ matrix.orm-version || 'none' }}, ${{ matrix.dependency-version }})
        steps:
            -   uses: actions/checkout@v4
            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    coverage: none
            -   name: Lock Doctrine ORM version
                run: composer require --no-interaction --no-progress --no-suggest --no-scripts --ansi --no-update doctrine/orm '${{ matrix.orm-version }}'
                if: matrix.orm-version != ''
            -   name: Install dependencies
                run: composer update --no-interaction --no-progress --no-suggest --no-scripts --ansi --${{ matrix.dependency-version}}
            -   name: Run test suite
                run: vendor/bin/phpunit
